language: node_js
node_js:
    - '0.10'
before_script:
    - cp config.js.sample config.js
    - mysql -e 'create database attendance_test;'
script:
    - make lint
    - make test
    - make build
sudo: false
